# Generated by Django 6.0.4 on 2026-05-25 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_author_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
    ]
