# Generated by Django 6.0.4 on 2026-05-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_email_address_author_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='email_address',
        ),
    ]
