name: Generate Pydoc

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositori
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instal·lar dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Executar les migracions
      run: |
        python manage.py migrate

    - name: Crear documentacio
      run: |
        mkdir -p docs
        export DJANGO_SETTINGS_MODULE=my_site.settings
        python manage.py shell -c "import django; django.setup()"
        python -m pydoc -w manage
        python -m pydoc -w blog.views
        mv *.html docs/

        echo "<h1>Documentació del projecte</h1>" > docs/index.html
        echo '<a href="manage.html">manage.py</a><br>' >> docs/index.html
        echo '<a href="blog.views.html">blog.views</a><br>' >> docs/index.html

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
